# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\Imagemap\:
    resource: '../Classes/*'

  Evoweb\Imagemap\Hooks\BackendHook:
    public: true

  Evoweb\Imagemap\Controller\Wizard\ImagemapManipulationController:
    public: true

  Evoweb\Imagemap\Database\SoftReferenceIndex:
    tags:
      - name: softreference.parser
        parserKey: imagemap